matrix:
  include:
  - name: "Ubuntu Xenial (16.04) with Python 2.7"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    virtualenv:
      system_site_packages: true
  - name: "Ubuntu Xenial (16.04) with Python 3.5"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.5
    virtualenv:
      system_site_packages: true
  - name: "Fedora Core 27 (Docker) with Python 2.7"
    env: FEDORA_VERSION="27"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 27 (Docker) with Python 3.6"
    env: FEDORA_VERSION="27"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Fedora Core 28 (Docker) with Python 2.7"
    env: FEDORA_VERSION="28"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 28 (Docker) with Python 3.6"
    env: FEDORA_VERSION="28"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Fedora Core 29 (Docker) with Python 2.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 29 (Docker) with Python 3.7"
    env: FEDORA_VERSION="29"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "MacOS with Python 2.7.10"
    os: osx
    language: generic
    env: PYTHONPATH=/Library/Python/2.7/site-packages/
  - name: "Pylint for Python 2.7 on Ubuntu Trusty (14.04)"
    env: TARGET="pylint2"
    os: linux
    dist: trusty
    sudo: required
    group: edge
    language: python
    python: 2.7
    virtualenv:
      system_site_packages: true
  - name: "Pylint for Python 2.7 on Ubuntu Xenial (16.04)"
    env: TARGET="pylint2"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    virtualenv:
      system_site_packages: true
install:
- if test "${TARGET}" != "pylint2"; then
    ./utils/travis.sh;
  fi
script:
- if test "${TARGET}" = "pylint2"; then
    sudo add-apt-repository ppa:gift/pylint2 -y;
    sudo apt-get update -q;
    sudo apt-get install -y pylint;
    pylint --version;
    git clone https://github.com/log2timeline/plaso.git;
    (cd plaso && find plaso/lib -name \*.py -exec pylint --rcfile=${PWD}/.pylintrc {} \;);
  elif test ${TRAVIS_OS_NAME} = "osx"; then
    git clone https://github.com/log2timeline/plaso.git;
    cd plaso && /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python ./utils/check_dependencies.py;
  elif test -n "${FEDORA_VERSION}"; then
    docker exec "fedora${FEDORA_VERSION}" sh -c "git clone https://github.com/log2timeline/plaso.git";
    if test ${TRAVIS_PYTHON_VERSION} = "2.7"; then
      docker exec "fedora${FEDORA_VERSION}" sh -c "cd plaso && python2 utils/check_dependencies.py";
    else
      docker exec "fedora${FEDORA_VERSION}" sh -c "cd plaso && python3 utils/check_dependencies.py";
    fi
  else
    git clone https://github.com/log2timeline/plaso.git;
    cd plaso && ./utils/check_dependencies.py;
  fi
